theme: jekyll-theme-minimal
title: Acacia L. Ackles
description: Please find enclosed relevant information for my dissertation defense, as well as irrelevant information that you might want to know anyway.
